services:
  frontend:
    image: mjsflames/quirknotes_frontend:latest
    ports:
    - "3000:3000"
  backend:
    image: mjsflames/quirknotes_backend:latest
    ports:
    - "4000:4000"
    environment:
    - ENV=Docker
    depends_on:
    - mongodb
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"